language: java

jdk:
  - oraclejdk8

test:
    post:
        - if [ -e ./gradlew ]; then ./gradlew jacocoTestReport;else gradle jacocoTestReport;fi
        - bash <(curl -s https://codecov.io/bash) -t d0e31c43-9bdc-48fd-9e86-7c3789d357d0
